wandb_version: 1

tabular:
  desc: null
  value: true
vision:
  desc: null
  value: resnet50
tabular_params:
  desc: null
  value:
    dim_input: 87
    hidden_dims:
    - 256
    - 512
    dropout_prob: 0.0
    batch_norm: true
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.35.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1702050944.3806
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 16
      - 23
      4: 3.8.18
      5: 0.16.1
      6: 4.35.2
      8:
      - 1
      - 5
      13: darwin-x86_64
