# Grid Search: DenseNet + Tabular
# Default hyperparameters taken from https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8189817/
# - Number of epochs: 10
# - Learning rate: 1e-3
program: multimodal/train.py
method: grid
project: biomed-team4
metric:
  goal: minimize
  name: eval_loss
command:
 - ${env}
 - python3
 - ${program}
 - ${args}
parameters:
  tabular: 
    value: 1 # == True
  vision: 
    value: 'densenet121' 
  hidden_dims: 
    value: '256-512' # Tune on tabular only
  dropout_prob: 
    value: 0.2
  lr: 
    values: [0.001]
  weight_decay:
    values: [0.001]
  num_epochs: 
    value: 10