# Grid Search: Tabular only
program: multimodal/train.py
method: grid
project: biomed-team4
metric:
  goal: minimize
  name: eval_loss
command:
 - ${env}
 - python3
 - ${program}
 - ${args}
parameters:
  tabular: 
    value: 1
  hidden_dims: 
    values: ['512', '256-512', '128-256-512']
  dropout_prob: 
    values: [0, 0.1]
  lr: 
    values: [.01, .001, .0001]
  weight_decay:
    values: [0, 0.01]
  num_epochs: 
    value: 20