# Grid Search: Vision Transformer only
program: multimodal/train.py
method: grid
project: biomed-team4
metric:
  goal: minimize
  name: eval_loss
command:
 - ${env}
 - python3
 - ${program}
 - ${args}
parameters:
  vision: 
    value: 'vit' 
  lr: 
    value: 0.0001
  num_epochs: 
    value: 10